
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.mycalculator.JflexYCup.Code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REAL_NUMEBERS = 8;
  public static final int SUMAR = 2;
  public static final int EOF = 0;
  public static final int MULTIPLICAR = 5;
  public static final int RESTAR = 3;
  public static final int DIVIDIR = 4;
  public static final int error = 1;
  public static final int PARENTESIS_C = 7;
  public static final int PARENTESIS_A = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMAR",
  "RESTAR",
  "DIVIDIR",
  "MULTIPLICAR",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "REAL_NUMEBERS"
  };
}

